### ISSUE TITLE
Target bootstrap value does not include reward?

### ISSUE THREAD

**Issue by Tony-chenjw** [zhaohengyin/EfficientImitate#1]
Hi, there. I have a question on the process of making target values. 

In the code (let's assume td_steps=1 here):
https://github.com/zhaohengyin/EfficientImitate/blob/a78246548064427d798548ad9f40127d2cf0dd1d/algo/state_ei/batch_worker.py#L358
According to my understanding, it calculates the target value in this way: $V_{targ}(s_t) \leftarrow \gamma * V_{targ}(s_{t+1})$

Shouldn't it be $V_{targ}(s_t) \leftarrow r(s_t, a_t) + \gamma * V_{targ}(s_{t+1})$ ?

By the way, I am running cheetah_state.sh.

Thanks for your reply in advance.

**Comment by zhaohengyin** [comment]
Thanks for the comment! Since we use the latest AIL reward rather than the groundtruth environment reward, we do not add the reward terms to the target in batch_worker computation. Instead, we add recomputed AIL reward terms at L387 at trainer.py.
