### ISSUE TITLE
Question on processing the expert data

### ISSUE THREAD

**Issue by Tony-chenjw** [zhaohengyin/EfficientImitate#2]
Hi, I have a question on the code here: https://github.com/zhaohengyin/EfficientImitate/blob/a78246548064427d798548ad9f40127d2cf0dd1d/algo/state_ei/replay_buffer.py#L69 

Why do we need this padding? Wouldn't it mess up the order when we select the subset from the expert data?https://github.com/zhaohengyin/EfficientImitate/blob/a78246548064427d798548ad9f40127d2cf0dd1d/algo/state_ei/replay_buffer.py#L243 By the way, I am running ``cheetah_state.sh``.
 
Could you explain it?  Thanks a lot.

**Comment by zhaohengyin** [comment]
We followed some conventions used in other open MuZero repositories which pad the action history at the beginning. This makes loss computation in trainer slightly cleaner. We apologize for any confusion. Thanks!
